// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

namespace Web.Migrations
{
    [DbContext(typeof(PlanningContext))]
    [Migration("20191224035626_2019-12-24-2")]
    partial class _201912242
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web.Models.DB.Job", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CollectTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("CompletionState")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DeleteState")
                        .HasColumnType("tinyint");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("JobID");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("Web.Models.DB.LifelongTarget", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(560)")
                        .HasMaxLength(560);

                    b.HasKey("UserID");

                    b.ToTable("LifelongTarget");
                });

            modelBuilder.Entity("Web.Models.DB.MonthTarget", b =>
                {
                    b.Property<int>("TargetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CollectTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("CompletionStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(140)")
                        .HasMaxLength(140);

                    b.Property<int>("MonthID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TargetID");

                    b.ToTable("MonthTarget");
                });

            modelBuilder.Entity("Web.Models.DB.Target", b =>
                {
                    b.Property<int>("TargetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CollectTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("CompletionStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(140)")
                        .HasMaxLength(140);

                    b.Property<byte>("TargetType")
                        .HasColumnType("tinyint");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TargetID");

                    b.ToTable("Target");
                });

            modelBuilder.Entity("Web.Models.DB.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("OpenID")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("RegIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnionID")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<int>("VipLevel")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Web.Models.DB.WeekTarget", b =>
                {
                    b.Property<int>("TargetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CollectTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("CompletionState")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DeleteState")
                        .HasColumnType("tinyint");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(140)")
                        .HasMaxLength(140);

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("WeekID")
                        .HasColumnType("int");

                    b.HasKey("TargetID");

                    b.ToTable("WeekTarget");
                });

            modelBuilder.Entity("Web.Models.DB.YearTarget", b =>
                {
                    b.Property<int>("TargetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CollectTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("CompletionState")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DeleteState")
                        .HasColumnType("tinyint");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(140)")
                        .HasMaxLength(140);

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("YearID")
                        .HasColumnType("int");

                    b.HasKey("TargetID");

                    b.ToTable("YearTarget");
                });
#pragma warning restore 612, 618
        }
    }
}
